version: 2

before:
  hooks:
    - go mod tidy
    - go tool templ generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

kos:
  - repositories:
      - ghcr.io/veggiemonk/cloud-run-iap
    bare: true
    base_image: cgr.dev/chainguard/static
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{.Tag}}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    creation_time: "{{.CommitTimestamp}}"
    sbom: none
    flags:
      - -trimpath
    ldflags:
      - -s -w
